[[game]]
name = 'Super Mario 64'

[[game.link]]
url = 'google.com/search?q=Koji+Kondo+Super+Mario+64'

[[game.link]]
url = 'wikipedia.org/wiki/Super_Mario_64'

[[game.link]]
text = 'RadiatorRampardos'
url = 'youtube.com/playlist?list=PLB4DC2508C4D0076D'

[[game.link]]
text = 'SilvaGunner'
url = 'youtube.com/playlist?list=PLu0fouVDrRZM1j1U4lTBgNnLbEX4R4Nld'

[[game.track]]
number = 9
name = 'Dire, Dire Docks'

[[game.track.link]]
text = 'RadiatorRampardos'
url = 'youtube.com/watch?v=Zqa2mgjbOIM'

[[game.track.link]]
text = 'Relaxing Piano - Super Mario 64 Underwater Theme'
url = 'youtube.com/watch?v=XRh0Z36RrWY'

[[game.track.link]]
text = 'SilvaGunner'
url = 'youtube.com/watch?v=N6G7uFlUyn4'

[[game.track]]
number = 35
name = 'staff roll'

[[game.track.link]]
text = 'RadiatorRampardos'
url = 'youtube.com/watch?v=o-xRxXYpavU'

[[game.track.link]]
text = 'SilvaGunner'
url = 'youtube.com/watch?v=_UmksF3MFXg'

[[game]]
name = 'Pilotwings 64'

[[game.link]]
url = 'wikipedia.org/wiki/Pilotwings_64'

[[game.link]]
url = 'youtube.com/playlist?list=PLWsnao9n727OfUwLfkm1bJjnkwxLNcSNH'
text = 'Pilotwings 64 HD'

[[game.link]]
url = 'youtube.com/playlist?list=PLWsnao9n727MUC1DSLXttRIASGxLmTRQb'
text = 'Pilotwings 64 HD Ultra'

[[game.link]]
url = 'youtube.com/playlist?list=PLWsnao9n727NrHIiqnZEtD180s9qxL4zl'
text = 'Pilotwings 64 Retro HD+'

[[game.track]]
number = 5
name = 'Hang Glider'

[[game.track.link]]
url = 'youtube.com/watch?v=h8-OfKFPnjw'
text = 'Pilotwings 64: Hang Glider'

[[game.track.link]]
url = 'youtube.com/watch?v=nv69iNJbqKo'
text = 'Pilotwings 64: Hang Glider HD'

[[game.track.link]]
url = 'youtube.com/watch?v=aaInC-vCjt0'
text = 'Pilotwings 64: Hang Glider Retro HD+'

[[game.track]]
number = 9
name = 'Rocket Belt'

[[game.track.link]]
url = 'youtube.com/watch?v=sAtiUoPB7d4'
text = 'Pilotwings 64: Rocket Belt'

[[game.track.link]]
url = 'youtube.com/watch?v=1QI0zjNZJtU'
text = 'Pilotwings 64: Rocket Belt HD'

[[game.track.link]]
url = 'youtube.com/watch?v=R9u06H6j8a0'
text = 'Pilotwings 64: Rocket Belt Retro HD+'

[[game.track]]
number = 20
name = 'Sky Diving'

[[game.track.link]]
url = 'youtube.com/watch?v=NDlyfygPZDs'
text = 'Pilotwings 64: Sky Diving'

[[game.track.link]]
url = 'youtube.com/watch?v=uARj6X14qE8'
text = 'Pilotwings 64: Sky Diving HD'

[[game.track.link]]
url = 'youtube.com/watch?v=cbb0ubUAJqc'
text = 'Pilotwings 64: Sky Diving Retro HD+'

[[game.track]]
number = 26
name = 'Birdman'

[[game.track.link]]
url = 'youtube.com/watch?v=DROiSgvFsRY'
text = 'Pilotwings 64: Birdman'

[[game.track.link]]
url = 'youtube.com/watch?v=bsUNUqk-JHg'
text = 'Pilotwings 64: Birdman HD'

[[game.track.link]]
url = 'youtube.com/watch?v=ar8oGTSg5Lk'
text = 'Pilotwings 64: Birdman Retro HD+'

[[game.track]]
number = 31
name = 'Bravissimo!'

[[game.track.link]]
url = 'youtube.com/watch?v=mziDsd_SE0M'
text = 'Pilotwings 64: Bravissimo!'

[[game.track.link]]
url = 'youtube.com/watch?v=mdHjSThrRYc'
text = 'Pilotwings 64: Bravissimo! HD'

[[game.track.link]]
url = 'youtube.com/watch?v=qzT0yKHN1f8'
text = 'Pilotwings 64: Bravissimo! Retro HD+'

[[game]]
name = 'Star Fox 64'

[[game.link]]
url = 'archive.org/details/starfox-64-soundtrack-cd'

[[game.link]]
url = 'wikipedia.org/wiki/Star_Fox_64'

[[game.track]]
number = 1
name = 'opening theme'

[[game.track.link]]
url = 'archive.org/details/starfox-64-soundtrack-cd/01+-+Opening+Theme.flac'

[[game.track]]
number = 2
name = 'title theme'

[[game.track.link]]
url = 'archive.org/details/starfox-64-soundtrack-cd/02+-+Title+Theme.flac'

[[game.track]]
number = 3
name = 'select theme'

[[game.track.link]]
url = 'archive.org/details/starfox-64-soundtrack-cd/03+-+Select+Theme.flac'

[[game]]
name = 'Super Mario Galaxy 2'

[[game.link]]
url = 'wikipedia.org/wiki/Super_Mario_Galaxy_2'

[[game.link]]
text = 'RadiatorRampardos'
url = 'youtube.com/playlist?list=PLC583980D7806298E'

[[game.track]]
number = 27
name = 'Cosmic Cove Galaxy'

[[game.track.link]]
url = 'youtube.com/watch?v=zcV7RptHqro'

[[game]]
name = 'Super Mario World'

[[game.link]]
url = 'wikipedia.org/wiki/Super_Mario_World'

[[game.link]]
text = 'SilvaGunner'
url = 'youtube.com/playlist?list=PLu0fouVDrRZNXc8DkkZR2Sx9N5wuotyrO'

[[game.track]]
number = 3
name = 'donut plains'

[[game.track.link]]
url = 'youtube.com/watch?v=sMqzn_bqK1Q'

[[game]]
name = "The Legend of Zelda: Majora's Mask"

[[game.link]]
url = "wikipedia.org/wiki/The_Legend_of_Zelda:_Majora's_Mask"

[[game.link]]
url = "zeldauniverse.net/media/music/majoras-mask-original-soundtrack"

[[game.track]]
number = 19
name = "cremia's carriage"

[[game.track.link]]
url = 'zeldauniverse.s3.amazonaws.com/soundtracks/majorasmaskost/cd2/2-19+Cremias+Carriage.mp3'

[[game]]
name = 'The Legend of Zelda: Ocarina of Time'

[[game.link]]
url = 'google.com/search?q=Koji+Kondo+The+Legend+of+Zelda:+Ocarina+of+Time'

[[game.link]]
url = 'wikipedia.org/wiki/The_Legend_of_Zelda:_Ocarina_of_Time'

[[game.link]]
url = 'zeldauniverse.net/media/music/ocarina-of-time-original-soundtrack'

[[game.link]]
text = 'Cha Chingo Christiano'
url = 'youtube.com/playlist?list=PLESFnlO3kNnpqtdBGrIl58Nn9OVzxhgLl'

[[game.track]]
number = 1
name = 'title theme'

[[game.track.link]]
url = 'youtube.com/watch?v=_dPCK3IPa7k'

[[game.track.link]]
url = 'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/01+-+Title+Theme.mp3'

[[game.track]]
number = 6
name = 'kokiri forest'

[[game.track.link]]
url = 'youtube.com/watch?v=rdaJ5pJmNfo'

[[game.track.link]]
url = 'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/06+-+Kokiri+Forest.mp3'

[[game.track]]
number = 12
name = 'inside the deku tree'

[[game.track.link]]
url = 'youtube.com/watch?v=WomOOpj-8o8'

[[game.track.link]]
url = 'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/12+-+Inside+The+Deku+Tree.mp3'

[[game.track]]
number = 19
name = 'hyrule field main theme'

[[game.track.link]]
url = 'youtube.com/watch?v=4h6kO9HVMaw'

[[game.track.link]]
url = 'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/19+-+Hyrule+Field+Main+Theme.mp3'

[[game.track]]
number = 28
name = 'lon lon ranch'

[[game.track.link]]
url = 'youtube.com/watch?v=q5Wq8DoYEmU'

[[game.track.link]]
url = 'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/28+-+Lon+Lon+Ranch.mp3'

[[game.track]]
number = 30
name = 'kakariko village'

[[game.track.link]]
url = 'youtube.com/watch?v=rS-Si8vsfbk'

[[game.track.link]]
url = 'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/30+-+Kakariko+Village.mp3'

[[game.track]]
number = 39
name = "zora's domain"

[[game.track.link]]
url = 'youtube.com/watch?v=JeJC2fxob0g'

[[game.track.link]]
url = 'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/39+-+Zoras+Domain.mp3'

[[game.track]]
number = 40
name = 'great fairy fountain'

[[game.track.link]]
url = 'youtube.com/watch?v=C3xHPcWxzXM'

[[game.track.link]]
url = 'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/40+-+Great+Fairy+Fountain.mp3'

[[game.track]]
number = 41
name = 'potion shop'

[[game.track.link]]
url = 'youtube.com/watch?v=_UN8OcTfOVA'

[[game.track.link]]
url = 'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/41+-+Potion+Shop.mp3'

[[game.track]]
number = 44
name = 'temple of time'

[[game.track.link]]
url = 'youtube.com/watch?v=Sv66WYSQPAc'

[[game.track.link]]
url = 'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/44+-+Temple+Of+Time.mp3'

[[game.track]]
number = 50
name = "sheik's theme"

[[game.track.link]]
url = 'youtube.com/watch?v=3iV8MkbGm2o'

[[game.track.link]]
url = 'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/50+-+Sheiks+Theme.mp3'

[[game.track]]
number = 57
name = 'windmill hut'

[[game.track.link]]
url = 'youtube.com/watch?v=ms9-vyV0HNo'

[[game.track.link]]
url = 'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/57+-+Windmill+Hut.mp3'

[[game.track]]
number = 68
name = 'gerudo valley'

[[game.track.link]]
url = 'youtube.com/watch?v=gmwdOH6fJ1s'

[[game.track.link]]
url = 'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/68+-+Gerudo+Valley.mp3'

[[game]]
name = 'The Legend of Zelda: The Wind Waker'

[[game.link]]
url = 'wikipedia.org/wiki/The_Legend_of_Zelda:_The_Wind_Waker'

[[game.link]]
url = 'zeldauniverse.net/media/music/the-wind-waker-original-soundtrack'

[[game.link]]
text = 'Rabbit OST'
url = 'youtube.com/playlist?list=PLH834K1pkcjJRwrw6j-Ah3FL48SDAsK_z'

[[game.track]]
number = 3
name = 'the legendary hero'

[[game.track.link]]
url = 'youtube.com/watch?v=jNuLYOMwdS0'

[[game.track.link]]
url = 'zeldauniverse.s3.amazonaws.com/soundtracks/thewindwakerost/cd1/The_Legend_of_Zelda_-_The_Wind_Waker_-_03_-_Legendary_Hero.mp3'

[[game.track]]
number = 38
name = 'dragon roost island'

[[game.track.link]]
url = 'youtube.com/watch?v=02pp7Pb7Bls'

[[game.track.link]]
url = 'zeldauniverse.s3.amazonaws.com/soundtracks/thewindwakerost/cd1/The_Legend_of_Zelda_-_The_Wind_Waker_-_38_-_Dragon_Island.mp3'

[[game]]
name = 'Donkey Kong Country 2'

[[game.link]]
url = 'wikipedia.org/wiki/Donkey_Kong_Country_2'

[[game.link]]
text = "Jammin' Sam Miller"
url = 'youtube.com/playlist?list=PLKNuUcvZGX23N53oLt93q4CZRj8m-Il_-'

[[game.track]]
number = 15
name = 'mining melancholy'

[[game.track.link]]
text = 'Donkey Kong Country 2 - Mining Melancholy [Restored]'
url = 'youtube.com/watch?v=cBK2YIrY62I'

[[game.track.link]]
text = 'Donkey Kong Country 2 - Mining Melancholy [Restored] 2023 Mix'
url = 'youtube.com/watch?v=qpJbv1JEA4I'

[[game.track]]
number = 19
name = 'stickerbush symphony'

[[game.track.link]]
text = 'Donkey Kong Country 2 - Stickerbush Symphony [Restored]'
url = 'youtube.com/watch?v=qIk6YFTzckc'

[[game.track.link]]
text = 'Donkey Kong Country 2 - Stickerbush Symphony [Restored] 2024 Mix'
url = 'youtube.com/watch?v=TxP2nqBIC44'

[[game.track]]
number = 23
name = 'forest interlude'

[[game.track.link]]
text = 'Donkey Kong Country 2 - Forest Interlude [Restored]'
url = 'youtube.com/watch?v=wxAZfLenfa0'

[[game.track.link]]
text = 'Donkey Kong Country 2 - Forest Interlude [Restored] 2025 Mix'
url = 'youtube.com/watch?v=AZOZXoDwCzI'

[[game]]
name = 'Mega Man X (video game)'

[[game.link]]
url = 'wikipedia.org/wiki/Mega_Man_X_(video_game)'

[[game.link]]
text = 'Frygoon'
url = 'youtube.com/playlist?list=PLLVedurB7ZPbdTRgvL53QN_0o8bWO9vL3'

[[game.track]]
number = 12
name = 'Chill Penguin (Snow Mountain Stage)'

[[game.track.link]]
text = 'Mega Man X OST - T12: Chill Penguin (Snow Mountain Stage)'
url = 'youtube.com/watch?v=fcOjHuAD6SI'

[[game.track.link]]
text = 'Mega Man X1 - Chill Peguin Stage(Jazz Remix)'
url = 'youtube.com/watch?v=etuuQyKuel4'
