[[game]]
name = 'Pilotwings 64'

[[game.link]]
url = 'wikipedia.org/wiki/Pilotwings_64'

[[game.link]]
url = 'youtube.com/playlist?list=PLWsnao9n727OfUwLfkm1bJjnkwxLNcSNH'
text = 'Pilotwings 64 HD'

[[game.link]]
url = 'youtube.com/playlist?list=PLWsnao9n727MUC1DSLXttRIASGxLmTRQb'
text = 'Pilotwings 64 HD Ultra'

[[game.link]]
url = 'youtube.com/playlist?list=PLWsnao9n727NrHIiqnZEtD180s9qxL4zl'
text = 'Pilotwings 64 Retro HD+'

[[game.track]]
number = 5

[[game.track.link]]
url = 'youtube.com/watch?v=h8-OfKFPnjw'
text = 'Hang Glider'

[[game.track.link]]
url = 'youtube.com/watch?v=nv69iNJbqKo'
text = 'Hang Glider HD'

[[game.track.link]]
url = 'youtube.com/watch?v=aaInC-vCjt0'
text = 'Hang Glider Retro HD+'

[[game.track]]
number = 9

[[game.track.link]]
url = 'youtube.com/watch?v=sAtiUoPB7d4'
text = 'Rocket Belt'

[[game.track.link]]
url = 'youtube.com/watch?v=1QI0zjNZJtU'
text = 'Rocket Belt HD'

[[game.track.link]]
url = 'youtube.com/watch?v=R9u06H6j8a0'
text = 'Rocket Belt Retro HD+'

[[game.track]]
number = 20

[[game.track.link]]
url = 'youtube.com/watch?v=NDlyfygPZDs'
text = 'Sky Diving'

[[game.track.link]]
url = 'youtube.com/watch?v=uARj6X14qE8'
text = 'Sky Diving HD'

[[game.track.link]]
url = 'youtube.com/watch?v=cbb0ubUAJqc'
text = 'Sky Diving Retro HD+'

[[game.track]]
number = 26

[[game.track.link]]
url = 'youtube.com/watch?v=bsUNUqk-JHg'
text = 'Pilotwings 64: Birdman HD'

[[game.track.link]]
url = 'youtube.com/watch?v=ar8oGTSg5Lk'
text = 'Pilotwings 64: Birdman Retro HD+'

[[game.track.link]]
url = 'youtube.com/watch?v=DROiSgvFsRY'
text = 'Pilotwings 64: Birdman'

[[game.track]]
number = 31

[[game.track.link]]
url = 'youtube.com/watch?v=mziDsd_SE0M'
text = 'Pilotwings 64: Bravissimo!'

[[game.track.link]]
url = 'youtube.com/watch?v=mdHjSThrRYc'
text = 'Pilotwings 64: Bravissimo! HD'

[[game.track.link]]
url = 'youtube.com/watch?v=qzT0yKHN1f8'
text = 'Pilotwings 64: Bravissimo! Retro HD+'

[[game]]
name = 'Star Fox 64'

[[game.link]]
url = 'archive.org/details/starfox-64-soundtrack-cd'

[[game.link]]
url = 'wikipedia.org/wiki/Star_Fox_64'

[[game.track]]
number = 1

[[game.track.link]]
url = 'archive.org/details/starfox-64-soundtrack-cd/01+-+Opening+Theme.flac'
text = 'opening theme'

[[game.track]]
number = 2

[[game.track.link]]
url = 'archive.org/details/starfox-64-soundtrack-cd/02+-+Title+Theme.flac'
text = 'title theme'

[[game.track]]
number = 3

[[game.track.link]]
url = 'archive.org/details/starfox-64-soundtrack-cd/03+-+Select+Theme.flac'
text = 'select theme'

[[game]]
name = 'Super Mario 64'

[[game.link]]
url = 'google.com/search?q=Koji+Kondo+Super+Mario+64'

[[game.link]]
url = 'wikipedia.org/wiki/Super_Mario_64'

[[game.link]]
text = 'RadiatorRampardos'
url = 'youtube.com/playlist?list=PLB4DC2508C4D0076D'

[[game.link]]
text = 'SilvaGunner'
url = 'youtube.com/playlist?list=PLu0fouVDrRZM1j1U4lTBgNnLbEX4R4Nld'

[[game.track]]
number = 9
name = 'Dire, Dire Docks'

[[game.track.link]]
url = 'youtube.com/watch?v=Zqa2mgjbOIM'
text = 'RadiatorRampardos'

[[game.track.link]]
url = 'youtube.com/watch?v=N6G7uFlUyn4'
text = 'SilvaGunner'

[[game.track]]
number = 35
name = 'staff roll'

[[game.track.link]]
url = 'youtube.com/watch?v=o-xRxXYpavU'
text = 'RadiatorRampardos'

[[game.track.link]]
url = 'youtube.com/watch?v=_UmksF3MFXg'
text = 'SilvaGunner'

[[game]]
name = 'Super Mario Galaxy 2'

[[game.link]]
url = 'wikipedia.org/wiki/Super_Mario_Galaxy_2'

[[game.link]]
url = 'youtube.com/playlist?list=PLC583980D7806298E'
text = 'RadiatorRampardos'

[[game.track]]
number = 27
name = 'Cosmic Cove Galaxy'

[[game.track.link]]
url = 'youtube.com/watch?v=zcV7RptHqro'

[[game]]
name = 'Super Mario World'

[[game.link]]
url = 'wikipedia.org/wiki/Super_Mario_World'

[[game.link]]
url = 'youtube.com/playlist?list=PLu0fouVDrRZNXc8DkkZR2Sx9N5wuotyrO'
text = 'SilvaGunner'

[[game.track]]
number = 3
name = 'donut plains'

[[game.track.link]]
url = 'youtube.com/watch?v=sMqzn_bqK1Q'

[[game]]
name = "The Legend of Zelda: Majora's Mask"

###

url = [
   "wikipedia.org/wiki/The_Legend_of_Zelda:_Majora's_Mask",
   "zeldauniverse.net/media/music/majoras-mask-original-soundtrack"
]

[[game.track]]
number = 19
name = "Cremia's Carriage"
url = [ 'zeldauniverse.s3.amazonaws.com/soundtracks/majorasmaskost/cd2/2-19+Cremias+Carriage.mp3' ]

[[game]]
name = 'The Legend of Zelda: Ocarina of Time'
url = [
  'google.com/search?q=Koji+Kondo+The+Legend+of+Zelda:+Ocarina+of+Time',
  'wikipedia.org/wiki/The_Legend_of_Zelda:_Ocarina_of_Time',
  'youtube.com/playlist?list=PLESFnlO3kNnpqtdBGrIl58Nn9OVzxhgLl',
  'zeldauniverse.net/media/music/ocarina-of-time-original-soundtrack'
]

[[game.track]]
number = 1
name = 'title theme'
url = [
   'youtube.com/watch?v=_dPCK3IPa7k',
   'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/01+-+Title+Theme.mp3'
]

[[game.track]]
number = 6
name = 'kokiri forest'
url = [
   'youtube.com/watch?v=rdaJ5pJmNfo',
   'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/06+-+Kokiri+Forest.mp3'
]

[[game.track]]
number = 12
name = 'inside the deku tree'
url = [
   'youtube.com/watch?v=WomOOpj-8o8',
   'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/12+-+Inside+The+Deku+Tree.mp3'
]

[[game.track]]
number = 19
name = 'hyrule field main theme'
url = [
   'youtube.com/watch?v=4h6kO9HVMaw',
   'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/19+-+Hyrule+Field+Main+Theme.mp3'
]

[[game.track]]
number = 28
name = 'lon lon ranch'
url = [
   'youtube.com/watch?v=q5Wq8DoYEmU',
   'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/28+-+Lon+Lon+Ranch.mp3'
]

[[game.track]]
number = 30
name = 'kakariko village'
url = [
   'youtube.com/watch?v=rS-Si8vsfbk',
   'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/30+-+Kakariko+Village.mp3'
]

[[game.track]]
number = 39
name = "zora's domain"
url = [
   'youtube.com/watch?v=JeJC2fxob0g',
   'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/39+-+Zoras+Domain.mp3'
]

[[game.track]]
number = 40
name = 'great fairy fountain'
url = [
   'youtube.com/watch?v=C3xHPcWxzXM',
   'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/40+-+Great+Fairy+Fountain.mp3'
]

[[game.track]]
number = 41
name = 'potion shop'
url = [
   'youtube.com/watch?v=_UN8OcTfOVA',
   'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/41+-+Potion+Shop.mp3'
]

[[game.track]]
number = 44
name = 'temple of time'
url = [
   'youtube.com/watch?v=Sv66WYSQPAc',
   'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/44+-+Temple+Of+Time.mp3'
]

[[game.track]]
number = 50
name = "sheik's theme"
url = [
   'youtube.com/watch?v=3iV8MkbGm2o',
   'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/50+-+Sheiks+Theme.mp3'
]

[[game.track]]
number = 57
name = 'windmill hut'
url = [
   'youtube.com/watch?v=ms9-vyV0HNo',
   'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/57+-+Windmill+Hut.mp3'
]

[[game.track]]
number = 68
name = 'gerudo valley'
url = [
   'youtube.com/watch?v=gmwdOH6fJ1s',
   'zeldauniverse.s3.amazonaws.com/soundtracks/ocarinaoftimeost/68+-+Gerudo+Valley.mp3'
]

[[game]]
name = 'The Legend of Zelda: The Wind Waker'
url = [
   'wikipedia.org/wiki/The_Legend_of_Zelda:_The_Wind_Waker',
   'youtube.com/playlist?list=PLH834K1pkcjJRwrw6j-Ah3FL48SDAsK_z',
   'zeldauniverse.net/media/music/the-wind-waker-original-soundtrack'
]

[[game.track]]
number = 3
name = 'the legendary hero'
url = [
   'youtube.com/watch?v=jNuLYOMwdS0',
   'zeldauniverse.s3.amazonaws.com/soundtracks/thewindwakerost/cd1/The_Legend_of_Zelda_-_The_Wind_Waker_-_03_-_Legendary_Hero.mp3'
]

[[game.track]]
number = 38
name = 'dragon roost island'
url = [
   'youtube.com/watch?v=02pp7Pb7Bls',
   'zeldauniverse.s3.amazonaws.com/soundtracks/thewindwakerost/cd1/The_Legend_of_Zelda_-_The_Wind_Waker_-_38_-_Dragon_Island.mp3'
]
[[game]]
name = 'Donkey Kong Country 2'
url = [
   'discogs.com/release/12927228-David-Wise-Donkey-Kong-Country-2-Diddys-Kong-Quest',
   'drive.google.com/drive/folders/1jUTvy4Bf81cFl8KxzBV0u2qz9WbL83Tm',
   'wikipedia.org/wiki/Donkey_Kong_Country_2',
   'youtube.com/playlist?list=PLKNuUcvZGX23N53oLt93q4CZRj8m-Il_-'
]

[[game.track]]
number = 15
name = 'mining melancholy'
url = [
   'youtube.com/watch?v=cBK2YIrY62I',
   'youtube.com/watch?v=qpJbv1JEA4I'
]

[[game.track]]
number = 19
name = 'stickerbush symphony'
url = [
   'youtube.com/watch?v=TxP2nqBIC44',
   'youtube.com/watch?v=qIk6YFTzckc'
]

[[game.track]]
number = 23
name = 'forest interlude'
url = [
   'youtube.com/watch?v=AZOZXoDwCzI',
   'youtube.com/watch?v=wxAZfLenfa0'
]

[[game]]
name = 'Mega Man X (video game)'
url = [
   'wikipedia.org/wiki/Mega_Man_X_(video_game)',
   'youtube.com/playlist?list=PLLVedurB7ZPbdTRgvL53QN_0o8bWO9vL3'
]

[[game.track]]
number = 12
name = 'Chill Penguin (Snow Mountain Stage)'
url = [
   'youtube.com/watch?v=etuuQyKuel4',
   'youtube.com/watch?v=fcOjHuAD6SI'
]
