package main

const (
   visitor_id = "CgtNbzlJR19GY24tNCjl_pDABjIKCgJVUxIEGgAgDA=="
   // kids
   // youtube.com/watch?v=QmpHcrA2hC0
   video_id = "QmpHcrA2hC0"
)

type ClientVersion struct {
   ID      int    `json:"id"`
   Name    string `json:"name"`
   Version string `json:"version"`
   Status  string `json:"status"`
}

var clients = []ClientVersion{
   {
      ID:      1,
      Name:    "WEB",
      Version: "2.20250829.01.00",
      Status:  "",
   },
   {
      ID:      1,
      Name:    "WEB",
      Version: "2.20220918",
      Status:  "",
   },
   {
      ID:      2,
      Name:    "MWEB",
      Version: "2.20250829.01.00",
      Status:  "",
   },
   {
      ID:      2,
      Name:    "MWEB",
      Version: "2.20220918",
      Status:  "",
   },
   {
      ID:      3,
      Name:    "ANDROID",
      Version: "20.34.37",
      Status:  "",
   },
   {
      ID:      3,
      Name:    "ANDROID",
      Version: "17.36.4",
      Status:  "",
   },
   {
      ID:      5,
      Name:    "IOS",
      Version: "20.34.2",
      Status:  "",
   },
   {
      ID:      5,
      Name:    "IOS",
      Version: "17.36.4",
      Status:  "",
   },
   {
      ID:      7,
      Name:    "TVHTML5",
      Version: "7.20241201.18.00",
      Status:  "",
   },
   {
      ID:      7,
      Name:    "TVHTML5",
      Version: "7.20220918",
      Status:  "",
   },
   {
      ID:      8,
      Name:    "TVLITE",
      Version: "2",
      Status:  "",
   },
   {
      ID:      10,
      Name:    "TVANDROID",
      Version: "1.0",
      Status:  "",
   },
   {
      ID:      13,
      Name:    "XBOXONEGUIDE",
      Version: "1.0",
      Status:  "",
   },
   {
      ID:      14,
      Name:    "ANDROID_CREATOR",
      Version: "20.34.100",
      Status:  "",
   },
   {
      ID:      14,
      Name:    "ANDROID_CREATOR",
      Version: "22.36.102",
      Status:  "",
   },
   {
      ID:      15,
      Name:    "IOS_CREATOR",
      Version: "20.34.x",
      Status:  "",
   },
   {
      ID:      15,
      Name:    "IOS_CREATOR",
      Version: "22.36.102",
      Status:  "",
   },
   {
      ID:      16,
      Name:    "TVAPPLE",
      Version: "1.0",
      Status:  "",
   },
   {
      ID:      18,
      Name:    "ANDROID_KIDS",
      Version: "7.36.1",
      Status:  "",
   },
   {
      ID:      19,
      Name:    "IOS_KIDS",
      Version: "7.36.1",
      Status:  "",
   },
   {
      ID:      21,
      Name:    "ANDROID_MUSIC",
      Version: "8.34.51",
      Status:  "",
   },
   {
      ID:      21,
      Name:    "ANDROID_MUSIC",
      Version: "5.26.1",
      Status:  "",
   },
   {
      ID:      23,
      Name:    "ANDROID_TV",
      Version: "6.18.303",
      Status:  "",
   },
   {
      ID:      23,
      Name:    "ANDROID_TV",
      Version: "2.19.1.303051424",
      Status:  "",
   },
   {
      ID:      26,
      Name:    "IOS_MUSIC",
      Version: "08.34",
      Status:  "",
   },
   {
      ID:      26,
      Name:    "IOS_MUSIC",
      Version: "5.26.1",
      Status:  "",
   },
   {
      ID:      27,
      Name:    "MWEB_TIER_2",
      Version: "2.20250829.01.00",
      Status:  "",
   },
   {
      ID:      27,
      Name:    "MWEB_TIER_2",
      Version: "9.20220918",
      Status:  "",
   },
   {
      ID:      28,
      Name:    "ANDROID_VR",
      Version: "1.37",
      Status:  "",
   },
   {
      ID:      29,
      Name:    "ANDROID_UNPLUGGED",
      Version: "6.36",
      Status:  "",
   },
   {
      ID:      30,
      Name:    "ANDROID_TESTSUITE",
      Version: "1.9",
      Status:  "",
   },
   {
      ID:      31,
      Name:    "WEB_MUSIC_ANALYTICS",
      Version: "0.2",
      Status:  "",
   },
   {
      ID:      33,
      Name:    "IOS_UNPLUGGED",
      Version: "6.36",
      Status:  "",
   },
   {
      ID:      38,
      Name:    "ANDROID_LITE",
      Version: "3.26.1",
      Status:  "",
   },
   {
      ID:      39,
      Name:    "IOS_EMBEDDED_PLAYER",
      Version: "2.4",
      Status:  "",
   },
   {
      ID:      41,
      Name:    "WEB_UNPLUGGED",
      Version: "2.20250829.01.00",
      Status:  "",
   },
   {
      ID:      41,
      Name:    "WEB_UNPLUGGED",
      Version: "1.20220918",
      Status:  "",
   },
   {
      ID:      42,
      Name:    "WEB_EXPERIMENTS",
      Version: "2.20250829.01.00",
      Status:  "",
   },
   {
      ID:      42,
      Name:    "WEB_EXPERIMENTS",
      Version: "1",
      Status:  "",
   },
   {
      ID:      43,
      Name:    "TVHTML5_CAST",
      Version: "1.1",
      Status:  "",
   },
   {
      ID:      55,
      Name:    "ANDROID_EMBEDDED_PLAYER",
      Version: "17.36.4",
      Status:  "",
   },
   {
      ID:      56,
      Name:    "WEB_EMBEDDED_PLAYER",
      Version: "2.20250829.01.00",
      Status:  "",
   },
   {
      ID:      56,
      Name:    "WEB_EMBEDDED_PLAYER",
      Version: "9.20220918",
      Status:  "",
   },
   {
      ID:      57,
      Name:    "TVHTML5_AUDIO",
      Version: "2.0",
      Status:  "",
   },
   {
      ID:      58,
      Name:    "TV_UNPLUGGED_CAST",
      Version: "0.1",
      Status:  "",
   },
   {
      ID:      59,
      Name:    "TVHTML5_KIDS",
      Version: "3.20220918",
      Status:  "",
   },
   {
      ID:      60,
      Name:    "WEB_HEROES",
      Version: "2.20250829.01.00",
      Status:  "",
   },
   {
      ID:      60,
      Name:    "WEB_HEROES",
      Version: "0.1",
      Status:  "",
   },
   {
      ID:      61,
      Name:    "WEB_MUSIC",
      Version: "2.20250829.01.00",
      Status:  "",
   },
   {
      ID:      61,
      Name:    "WEB_MUSIC",
      Version: "1.0",
      Status:  "",
   },
   {
      ID:      62,
      Name:    "WEB_CREATOR",
      Version: "2.20250829.01.00",
      Status:  "",
   },
   {
      ID:      62,
      Name:    "WEB_CREATOR",
      Version: "1.20220918",
      Status:  "",
   },
   {
      ID:      63,
      Name:    "TV_UNPLUGGED_ANDROID",
      Version: "1.37",
      Status:  "",
   },
   {
      ID:      64,
      Name:    "IOS_LIVE_CREATION_EXTENSION",
      Version: "17.36.4",
      Status:  "",
   },
   {
      ID:      65,
      Name:    "TVHTML5_UNPLUGGED",
      Version: "6.36",
      Status:  "",
   },
   {
      ID:      66,
      Name:    "IOS_MESSAGES_EXTENSION",
      Version: "17.36.4",
      Status:  "",
   },
   {
      ID:      67,
      Name:    "WEB_REMIX",
      Version: "2.20250829.01.00",
      Status:  "",
   },
   {
      ID:      67,
      Name:    "WEB_REMIX",
      Version: "1.20220918",
      Status:  "",
   },
   {
      ID:      68,
      Name:    "IOS_UPTIME",
      Version: "1.0",
      Status:  "",
   },
   {
      ID:      69,
      Name:    "WEB_UNPLUGGED_ONBOARDING",
      Version: "2.20250829.01.00",
      Status:  "",
   },
   {
      ID:      69,
      Name:    "WEB_UNPLUGGED_ONBOARDING",
      Version: "0.1",
      Status:  "",
   },
   {
      ID:      70,
      Name:    "WEB_UNPLUGGED_OPS",
      Version: "2.20250829.01.00",
      Status:  "",
   },
   {
      ID:      70,
      Name:    "WEB_UNPLUGGED_OPS",
      Version: "0.1",
      Status:  "",
   },
   {
      ID:      71,
      Name:    "WEB_UNPLUGGED_PUBLIC",
      Version: "2.20250829.01.00",
      Status:  "",
   },
   {
      ID:      71,
      Name:    "WEB_UNPLUGGED_PUBLIC",
      Version: "0.1",
      Status:  "",
   },
   {
      ID:      72,
      Name:    "TVHTML5_VR",
      Version: "0.1",
      Status:  "",
   },
   {
      ID:      73,
      Name:    "WEB_LIVE_STREAMING",
      Version: "2.20250829.01.00",
      Status:  "",
   },
   {
      ID:      74,
      Name:    "ANDROID_TV_KIDS",
      Version: "1.19.1",
      Status:  "",
   },
   {
      ID:      75,
      Name:    "TVHTML5_SIMPLY",
      Version: "1.0",
      Status:  "",
   },
   {
      ID:      76,
      Name:    "WEB_KIDS",
      Version: "2.20250829.01.00",
      Status:  "",
   },
   {
      ID:      76,
      Name:    "WEB_KIDS",
      Version: "2.20220918",
      Status:  "",
   },
   {
      ID:      77,
      Name:    "MUSIC_INTEGRATIONS",
      Version: "0.1",
      Status:  "",
   },
   {
      ID:      80,
      Name:    "TVHTML5_YONGLE",
      Version: "0.1",
      Status:  "",
   },
   {
      ID:      84,
      Name:    "GOOGLE_ASSISTANT",
      Version: "0.1",
      Status:  "",
   },
   {
      ID:      85,
      Name:    "TVHTML5_SIMPLY_EMBEDDED_PLAYER",
      Version: "2.0",
      Status:  "",
   },
   {
      ID:      86,
      Name:    "WEB_MUSIC_EMBEDDED_PLAYER",
      Version: "2.20250829.01.00",
      Status:  "",
   },
   {
      ID:      87,
      Name:    "WEB_INTERNAL_ANALYTICS",
      Version: "2.20250829.01.00",
      Status:  "",
   },
   {
      ID:      87,
      Name:    "WEB_INTERNAL_ANALYTICS",
      Version: "0.1",
      Status:  "",
   },
   {
      ID:      88,
      Name:    "WEB_PARENT_TOOLS",
      Version: "2.20250829.01.00",
      Status:  "",
   },
   {
      ID:      88,
      Name:    "WEB_PARENT_TOOLS",
      Version: "1.20220918",
      Status:  "",
   },
   {
      ID:      89,
      Name:    "GOOGLE_MEDIA_ACTIONS",
      Version: "0.1",
      Status:  "",
   },
   {
      ID:      90,
      Name:    "WEB_PHONE_VERIFICATION",
      Version: "2.20250829.01.00",
      Status:  "",
   },
   {
      ID:      90,
      Name:    "WEB_PHONE_VERIFICATION",
      Version: "1.0.0",
      Status:  "",
   },
   {
      ID:      93,
      Name:    "TVHTML5_FOR_KIDS",
      Version: "7.20220918",
      Status:  "",
   },
   {
      ID:      94,
      Name:    "GOOGLE_LIST_RECS",
      Version: "0.1",
      Status:  "",
   },
   {
      ID:      95,
      Name:    "MEDIA_CONNECT_FRONTEND",
      Version: "0.1",
      Status:  "",
   },
   {
      ID:      98,
      Name:    "WEB_EFFECT_MAKER",
      Version: "2.20250829.01.00",
      Status:  "",
   },
   {
      ID:      99,
      Name:    "WEB_SHOPPING_EXTENSION",
      Version: "2.20250829.01.00",
      Status:  "",
   },
   {
      ID:      100,
      Name:    "WEB_PLAYABLES_PORTAL",
      Version: "2.20250829.01.00",
      Status:  "",
   },
   {
      ID:      102,
      Name:    "WEB_LIVE_APPS",
      Version: "2.20250829.01.00",
      Status:  "",
   },
   {
      ID:      103,
      Name:    "WEB_MUSIC_INTEGRATIONS",
      Version: "2.20250829.01.00",
      Status:  "",
   },
}
